
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.notebook.analizadorTexto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HEADER = 2;
  public static final int LISTA = 6;
  public static final int ITALIC = 5;
  public static final int EOF = 0;
  public static final int BOLD = 4;
  public static final int NUM_PUNTO = 7;
  public static final int error = 1;
  public static final int BOLD_ITALIC = 3;
  public static final int PARRAFO = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEADER",
  "BOLD_ITALIC",
  "BOLD",
  "ITALIC",
  "LISTA",
  "NUM_PUNTO",
  "PARRAFO"
  };
}

